# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  cabeza_motor1:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  cuerpo1_motor2:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  cuerpo2_motor3:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  cuerpo3_motor4:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  motor1_cuerpo1:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  motor2_cuerpo2:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  motor3_cuerpo3:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0
  motor4_cola:
    has_velocity_limits: true
    max_velocity: 3
    has_acceleration_limits: false
    max_acceleration: 0